### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by MichalK6677** [MurhafSousli/ngx-scrollbar#120]
Will be there a support for IE11? Even example is not working in IE:
https://murhafsousli.github.io/ngx-scrollbar/

**Comment by MurhafSousli** [comment]
Unfortunately not, there is no plan to support IE11

**Comment by anuragyg** [comment]
Hi.
I know there is a wontfix label attached to this but it will really be great if IE11 is supported too since IE11 is also used. I have been using the scrollbar since it was in Version 2.1 and with the recent upgrades its not easy to make changes in an already existing app. 
It will be great if assistance for IE11 can be provided in the upcoming versions. 👍
