### ISSUE TITLE
Smooth scroll problems

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-scrollbar#186]
#### Reproduction

When duration is 0, smooth scroll function does not work properly

While debugging I found that the top was equal to `-infinity`

https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/smooth-scroll/src/smooth-scroll-manager.ts#L75

Steps to reproduce:

Use the smooth scroll function `scrollable.scrollToBottom();`
 
#### Expected Behavior
Scroll to bottom instantly.

#### Actual Behavior
It doesn't scroll, or if scroll position was in middle, it scrolls to top

#### Environment

- Angular: 8
- ngx-scrollbar: 5.0.1

**Comment by Nyconing** [comment]
Hi. This issue needs to be **top priority**.
Human observable glitches (without look into codes):
1. This glitches/ artifact can be reproduced in whatever value of duration, not just 0
2. Last frame of smooth scroll animation is missing
3. Last frame of animate shall bring scroll to targeted value, but it was missing, causing glitches when there is some duration
4. Scroll dont work at all when duration is 0, just simply because of animation is skipped and last frame is missing

**Comment by MurhafSousli** [comment]
I am working on it

**Comment by Nyconing** [comment]
Hi, an update.
Im fixing it by define custom easing method.

```
  "bezier-easing": "^2.1.0"
  ...
  import * as BezierEasing from 'bezier-easing';
  ...
  myEaseInOutQuad(t: number, b: number, c: number, d: number) {
    let float = BezierEasing.default(0, 0, .5, 1)(t/d);
    return float<0 || float>1 ? b+c : b+(float*c); //not sure why float sometime can be negative (bugs?)
  }
  ...
  scrollable.scrollTo({ top: 700, left:300, duration: 0, easeFunc :myEaseInOutQuad })
```
Scrolling is now working perfectly. But facing new issue, the scrollbar dont move at the beginning (facepalm)

1. Scrollbar wont move
2. Scrollbar moving again after the scrollbar moved by user

**Comment by Nyconing** [comment]
Also, you may consider using bezier-easing, so user may configure the smooth scroll animation easier, by given the bezier param instead of easeFunc.
