### ISSUE TITLE
scrollTo functions does not work in v5

### ISSUE THREAD

**Issue by qaxqaxqax** [MurhafSousli/ngx-scrollbar#210]
#### Reproduction

(forked your stack)
https://stackblitz.com/edit/ngx-scrollbar-bbi7kw?file=src/app/scroll-event/scroll-event/scroll-event.component.ts

Steps to reproduce:
1. Add some selectable DOM into ngx-scrollbar -> `<div class="a">a</div>`

2. Connect with ref in .ts -> `@ViewChild(NgScrollbar, { static: true }) scrollbarRef: NgScrollbar;`
3. Try to scroll -> `this.scrollbarRef.scrollToElement(this.scrollbarRef.viewport.querySelector('div.a'));`

(scrollToSelector share the same issue)
 
 
#### Expected Behavior

Reveal the scroll postion where div.a is.

#### Actual Behavior

It does not scroll

#### Environment

- Angular: 8.3.2
- ngx-scrollbar: 5.0.2
- Browser(s): Tested it in Chrome (76.0)
- Operating System: macOS

**Comment by MurhafSousli** [comment]
This bug is related to #186 and it is already fixed.

For now you can set a duration to get around it `this.scrollbarRef.scrollToElement(this.scrollbarRef.viewport.querySelector('div.a'),0, 500);`

[fixed stackblitz](https://stackblitz.com/edit/ngx-scrollbar-jytbya?file=src/app/scroll-event/scroll-event/scroll-event.component.ts)

Stay tuned for the next update

**Comment by MurhafSousli** [comment]
You can now upgrade to v6.0.0 where these issues are solved

**Comment by qaxqaxqax** [comment]
> You can now upgrade to v6.0.0 where these issues are solved

Thank you. By the way I got something in mind to solve the 'standard' problem. Can I reply on the relevant closed ticket?
