### ISSUE TITLE
appearance:standard does not work when content width exceeds 100%

### ISSUE THREAD

**Issue by qaxqaxqax** [MurhafSousli/ngx-scrollbar#211]
#### Reproduction

https://stackblitz.com/edit/ngx-scrollbar-l7ugb6?file=src/app/home/home.component.html

Steps to reproduce:
1. Use `[appearance]="'standard'"` input on ngx-scrollbar
2. Add some style to make it more visible
 
 
#### Expected Behavior

Make the scrollbar tracks to wrap around the scroll area like a system scrollbar.

#### Actual Behavior

The actual behaviour is like a compact scrollbar with some extra padding on the bottom of the content.

#### Environment

- Angular: 8.3.2
- ngx-scrollbar: 5.0.2
- Browser(s): Chrome (76.0)
- Operating System: macOS

**Comment by MurhafSousli** [comment]
Okay let me explain something, since #168 we wanted to enable scrolling when the mouse is over the scrollbar, this meant refactoring the layout.

Before the scrollbar was next to the scroll area but over it
Scroll area was positioned using  `absolute + right`, however scrolling when mouse is over the scrollbar won't scroll. see https://stackblitz.com/edit/ngx-scrollbar-v4

Now the scrollbar has to be inside the scroll area, therefore we use `padding-right` on scroll area to push the content to achieve the standard appearance.

The problem with padding is that when the content width exceeded `100%` it cannot be wrapped like the stackblitz you shared.

You can play around with the content width and the standard appearance in the demo lab https://ngx-scrollbar.netlify.com/

So currently the standard appearance only work if the content width didn't exceed `100%` like in here https://stackblitz.com/edit/ngx-scrollbar-yetvxf?file=src/app/home/home.component.html

I had to give away the standard appearance when content width is wider for the sake of #168 

If you figure out a way to make both work, please send me a PR

**Comment by MurhafSousli** [comment]
That would not work, the actual scroll area has to be natively scrolled. Using `onWheel` would cancel the native scrolling mechanism which many features of the component rely on it

**Comment by qaxqaxqax** [comment]
Okay you are right. I was a little bit hacky here. Thank you for the quick responses and the awesome tool. :) If I have any other idea I will reply.

**Comment by MurhafSousli** [comment]
Will do, Thanks a lot!
