### ISSUE TITLE
Bug in the lab on the demo site

### ISSUE THREAD

**Issue by rooby** [MurhafSousli/ngx-scrollbar#257]
#### Reproduction

In the lab on the demo site (https://ngx-scrollbar.netlify.com/), when you load the page the vertical scrollbar on the middle section of text overlaps the text.

I'm currently in Chrome.

**Comment by MurhafSousli** [comment]
This is by design. by default, the appearance option is set to `compact`, if you don't want it to overlap, use `appearance ="standard"`

You may want to read this [note](https://github.com/MurhafSousli/ngx-scrollbar/wiki/pointer-events#in-a-nutshell-here-are-the-pros-and-cons-of-each-method-with-the-appearance-option) if you are using both directions

**Comment by rooby** [comment]
Oh right, thanks for the quick reply.

I really need to update to the latest version, it looks great.
Thanks for all your work on this project, it's excellent.
