### ISSUE TITLE
Small scrollbar flicker when adding elements to the DOM

### ISSUE THREAD

**Issue by sebastientromp** [MurhafSousli/ngx-scrollbar#259]
Hello,

When adding some elements to the DOM, I see a brief flickering of the scrollbar, as illustrated in the gif below:

![scrollbar flicker](https://user-images.githubusercontent.com/7889624/72157419-2b334200-33b8-11ea-82b9-5164025b9136.gif)

`isVerticallyScrollable` briefly becomes `true` before being `false` again (which is the expected state).

Do you have any idea what might cause this flicker?
  
#### Environment

- Angular: 8.1.1
- ngx-scrollbar: 7.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment]
Hi @sebastientromp, I actually never came across this issue before even that I used it in dropdown component.

As you can see in the source code, `isVerticallyScrollable` state becomes true when `viewport.scrollHeight > viewport.clientHeight`

https://github.com/MurhafSousli/ngx-scrollbar/blob/e8c9dc3875ccde845d38a1be6031092992ce763c/projects/ngx-scrollbar/src/lib/ng-scrollbar.ts#L145-L148

This means that there is a time where the viewport scrollHeight becomes larger than the viewport clientHeight which is caused by clicking on the dropdown component.

Until now I can say that this behavior is caused by the component your using for some mystiyrous reason, but it's caused by `ng-scrollbar` then I would like to get it fixed!

Did you try to disable `ng-scrollbar` and see if the native scrollbar will cause the same flicker?

I can also think of a CSS workaround that would delay showing the scrollbar

```scss
.scrollbar-control {
  animation: fadein 400ms linear 1 normal forwards;
}

@keyframes fadein{
  0% { opacity: 0;}
  80% { opacity: 0;}
  100% { opacity: 1;}
}
```

**Comment by sebastientromp** [comment]
Hey, thanks a lot for the quick and detailed answer!
The CSS workaround works well, that's perfect. I'll check if I can reproduce it with native scrollbars as well and will keep you updated (you can close the issue though).

Thanks a lot!

**Comment by MurhafSousli** [comment]
Hey, can you try it again with v3.7.4 (without the workaround) and see if it still flickers?
