### ISSUE TITLE
Problem with scroll start position

### ISSUE THREAD

**Issue by BogdanPolandUkraine** [MurhafSousli/ngx-scrollbar#302]
#### Reproduction

I have a problem with a start position of scroll in a list, the visibility of which I can control using a button:
https://stackblitz.com/edit/angular-ivy-2kaj63

Steps to reproduce:
1. Open project stackblitz
2. List is unvisible
3. Click button "Change list visibility"
4. List is visible
5. Scroll to the end of list. Scroll has style: 
    height: 40px;
    transform: translate3d(0px, 112px, 0px);
6. Click button "Change list visibility"
7. List is unvisible
8. Click button "Change list visibility"
9. List is visible, but scroll is smaller - start position of scroll should be higher then I have. Scroll has style:
    height: 40px;
    transform: translate3d(0px, 126px, 0px);
But style should be like previously:
    height: 40px;
    transform: translate3d(0px, 112px, 0px);

#### Expected Behavior
When list is visible again, scrolls full height should be visible (not piece of height)

I think, library has a problem with calculate style 'transform'. 
If I have something wrong in html file, can you correct it or say me what should I do?
 
#### Environment

- Angular: like in project stackblitz
- ngx-scrollbar: like in project stackblitz
- Browser(s): Firefox 68.9.0 or Chrome 84.0.4147.105
- Operating System (Windows): 10

**Comment by MurhafSousli** [comment]
I opened the stackblitz and it seems to be working as expected! the height is always 160px

**Comment by BogdanPolandUkraine** [comment]
I don't talk about component, but about scroll - scrollbar in component.
I attached video, in which you can see how change height of scroll (scrollbar) in component.
![record_000001](https://user-images.githubusercontent.com/69465126/89864284-fe444900-dbab-11ea-8992-da23109313b7.gif)

**Comment by MurhafSousli** [comment]
There is no wrong calculation in the scrollbar thumb size, it gets updated on different events, mostly on `AfterViewChecked`, 

in your reproduction, is there a reason that you used `[style.display]` instead of `*ngIf`?

on some browsers working on a relatively slow machine, it is possible that `ngAfterViewChecked` is fired before the list inside the scrollbar had been completed rendered, were the position was not reset, and that could be cause by conflict with the previously set values that were not reset since you only hided the DOM and didn't destroy the component

If for what ever reason you need to use `[style.display]` to show/hide the component then I suggest that you trigger the update function manually, like in this example https://stackblitz.com/edit/angular-ivy-1lmnqq?file=src%2Fapp%2Fapp.component.ts

**Comment by BogdanPolandUkraine** [comment]
I used your stackblitz (but didn't save it) and changed it to use *ngIf instead [style.display]. And everytime, when I changed list visibility, scrollbar thumb was going to top. 
But I need: the scrollbar thumb stay in the same position with same height, when I change the visibility of the list. 
So, I think I will use your stackblitz. Or can you propose something else?

**Comment by MurhafSousli** [comment]
@BogdanPolandUkraine I can't think of any alternative, but the workaround will work fine
