### ISSUE TITLE
Release 9.0.1?

### ISSUE THREAD

**Issue by MaximeKoitsalu** [MurhafSousli/ngx-scrollbar#420]
Hello,

Any ETA for when 9.0.1 will be released? Am waiting for 7.4.0 rxjs peerDependency

Cheers!
Thanks for developing this lib.

**Comment by NashIlli** [comment]
+1 thanks!

**Comment by MurhafSousli** [comment]
Sorry guys, I am on a new laptop and I am stuck with an annoying npm error when I try to publish the package since couple of days. I cloned the repo with GH CLI got the error, then tried SSH then HTTPS... I did generate an SSH and it work in my NPM

![image](https://user-images.githubusercontent.com/8130692/148104053-5ee88529-878b-435c-8d95-edf1bb2a33ea.png)

**Comment by MurhafSousli** [comment]
Ok, it seems that I cannot use `npm publish dist/ngx-scrollbar` because strangely it modifies the ssh url to push the package to npm or something like that. so I had to cd into `dist/ngx-scrollbar` and then run `npm publish` 

The new version is out!
