### ISSUE TITLE
Scrollbar does not update when resizing the window

### ISSUE THREAD

**Issue by linhkk3214** [MurhafSousli/ngx-scrollbar#546]
#### Reproduction

https://stackblitz.com/edit/ngx-scrollbar-yo2p4e?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:
1. Change window size to show/hide scrollbar
 

#### Expected Behavior

If the container contains the whole content, the scrollbar must be hidden

#### Actual Behavior

The scrollbar doesn't change anything (It keeps the first state)

#### Environment

- Angular: v16
- ngx-scrollbar: v13
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Window

**Comment by MurhafSousli** [comment]
Can you try the latest version?

**Comment by MurhafSousli** [comment]
This seem to be a bug in v13.0.2, but it is fixed in v14, see this [stackblitz](https://stackblitz.com/edit/stackblitz-starters-sh4gux?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=package.json&template=node&title=Angular%20Starter)

**Comment by linhkk3214** [comment]
> Try setting the max-height on the component
This solution doesn't work.

> This works out of the box in v14, I highly recommend upgrading to angular 17 to use it
I already used angular v17. I will try upgrading to v14 to check if it works.

**Comment by linhkk3214** [comment]
When I update to v14, where is the event "scrollbar.scrolled"?

**Comment by MurhafSousli** [comment]
I guess we can close this as fixed in v14
