### ISSUE TITLE
Font Awesome icons wont load correctly in Firefox

### ISSUE THREAD

**Issue by MarcelReichelt** [MurhafSousli/ngx-scrollbar#581]
When using ngx-scrollbar in conjunction with [@fortawesome/fontawesome-free](https://www.npmjs.com/package/@fortawesome/fontawesome-free) in Firefox, the icons break as soon as a scrollbar is displayed.
We had also observed issues with the scrollbar itself, where the thumb wont move as you scroll (see Stackblitz preview, open in Firefox).

There was a similar issue [here](https://github.com/MurhafSousli/ngx-scrollbar/issues/558), but it was closed due to no reproduction examples.

#### Reproduction

I created a repository on [GitHub](https://github.com/MarcelReichelt/ng-scrollbar-firefox-issue-minimal) ([Stackblitz](https://stackblitz.com/~/github.com/MarcelReichelt/ng-scrollbar-firefox-issue-minimal)).

Steps to reproduce:
1. Have Font Awesome Icons
2. Get a ngx-scrollbar to display
3. The icons break as soon as the scrollbar gets loaded
 
 
#### Actual Behavior / Expected Behavior

![Screenshot 2024-04-20 053722](https://github.com/MurhafSousli/ngx-scrollbar/assets/15636193/f38a536c-22b0-4610-a80e-03e2c6fb2311)

On the left you can see the (actual) behavior in Firefox, on the right the (expected) behavior in Edge.

Here you can see the scrollbar thumb issue:

![Screenshot 2024-04-20 063131](https://github.com/MurhafSousli/ngx-scrollbar/assets/15636193/60d80fff-3544-4a6a-83e7-93a3ceaba6cd)

As the content is scrolled, the thumb should be in another location.

#### Environment

- Angular: 17.3.0
- ngx-scrollbar: 14.1.0
- @fortawesome/fontawesome-free: 6.5.2
- Browser(s): Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): confirmed on Windows 11 and Ubuntu (not sure which version right now, but pretty recent), but i guess it does not mater

**Comment by MurhafSousli** [comment]
1. Your reproduction worked in my Firefox, 2. why not use angular font-awesome library for the icons?

**Comment by MarcelReichelt** [comment]
Ok, we also had the issue outside of the Stackblitz environment, but this may be related to other issues. 

What about the icon issue? Any idea on how to deal with this?

**Comment by MurhafSousli** [comment]
I check your reproduction link on my firefox, the icons are displayed

**Comment by MurhafSousli** [comment]
This is not related to this plugin, it works when I use angular fontawesome component.

https://github.com/MurhafSousli/ngx-scrollbar/assets/8130692/bb4924c5-5469-410a-8ce8-7f0c379c8d8a

**Comment by afomichenko** [comment]
@MurhafSousli, we are also experiencing the same issue in **Firefox** with the latest version of **ngx-scrollbar** (v15.0.1):

<img width="754" alt="image" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/3300451/1d9ffc7a-ab7a-4370-bd61-7fd309adac73">

The FontAwesome icons disappear only on those pages that contain an instance of ngx-scrollbar.

Here's another (and most likely related) anomaly that we have noticed on pages where ngx-scrollbar is present, and all this happens within a second or so:

1) The page loads fine (including the FontAwesome icons)
2) All CSS appears removed from the page for a split second (because we see bare unstyled HTML)
3) The CSS is restored, except for the FontAwesome

This does not happen if we downgrade to version **13.0.3**.

**Comment by MurhafSousli** [comment]
@afomichenko the latest version is built from scratch. So it depends how you are loading the icons, for example if you are using a function that loads the icons on app init, at the time the scrollbar component hasn't rendered its content yet, it could miss to load the icons inside.

Are you using fontawesome component?

In anyway, you need to have a reproduction, if you want me to look into it.

**Comment by afomichenko** [comment]
@MurhafSousli The interesting thing is that this issue affects areas on the page that have nothing to do with the scrollbar. In my example, it's the top navigation. The mere presence of the scrollbar on the page causes all icons on that page to disappear, even those outside the scrollbar.

We're using the FontAwesome Pro version and are referencing the icons by class name:

<img width="470" alt="image" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/3300451/94fd6856-eba5-4a1b-bb3e-c9343d10950d">

**Comment by MurhafSousli** [comment]
Everyone who is having this issue is using the legacy CSS method of FontAwesome. The legacy way is problematic with Angular that's why they made an Angular component with SVG icons instead of the CSS method.

Follow this https://docs.fontawesome.com/web/use-with/angular/ and you will not have any issue.

**Comment by afomichenko** [comment]
I have not found any support for the claim that the CSS method of using FontAwesome with Angular is "legacy" or "problematic". The Angular component was made as an option, an alternative, allegedly more convenient way, not as a recommended replacement for the CSS method.

To re-iterate, the CSS FontAwesome icons work great in Angular with no issues whatsoever, until a **ngx-scrollbar** (version 14 and up) is included somewhere on the page.

**Comment by MurhafSousli** [comment]
@afomichenko Of course, they won't say that about their commercial product on their website!

It is legacy because it is the original usage +10 years ago. it can be problematic when used with JS framework.

![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/8130692/5edc5b48-dbe3-4015-928e-44f5b92dfdeb)


Anyway, as you wish. from my side, I don't see an issue with the code nor willing to investigate why another library is failing when used in CSS mode.

Feel free to investigate the issue yourself, if you figure out what is wrong in this library you can let me know and I can look into it, or you can try opening an issue on their repository, maybe its a known issue with other libraries. or use the old version or just use another library.

**Comment by afomichenko** [comment]
@MurhafSousli I just updated to **15.1.2** and this issue is now resolved. The FontAwesome icons now function with no issue. I hope you can acknowledge that using the "legacy" CSS method of FontAwesome had nothing to do with this issue.

**Comment by MurhafSousli** [comment]
@afomichenko  The scrollbar plugin has nothing to do with it as well, it's the polyfill that was modifying the global styles in some way. I still think the SVG icons are the way to go https://docs.fontawesome.com/web/dig-deeper/webfont-vs-svg, if you were using SVG method you wouldn't have got an issue.
