### ISSUE TITLE
Scroll Bar thumb not moving

### ISSUE THREAD

**Issue by krupakaran1987** [MurhafSousli/ngx-scrollbar#60]
I trying to integrate ngx-scroll bar with angular5. in my case i can able to add ngx-scroll bar in component. When i scroll using mouse the content was scrolling exactly but the thumb is in **freeze**. 

![scroll bar](https://user-images.githubusercontent.com/33723373/45693356-88c7cd80-bb7a-11e8-9c02-33ba802cdd36.png)

**Comment by MurhafSousli** [comment]
Hi @krupakaran1987 Please fill the issue template properly, because I don't know which version of the plugin you are using and It is unclear if there is an error.

Generally you go the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md), see the last update for angular 5 which is ngx-scrollbar@**1.5.7**

Therefor you either use that version as it is with your angular 5 app, or use the latest version with `npm i rxjs-compat`

or just upgrade to Angular 6 :)
