### ISSUE TITLE
Kendo UI Grid Component

### ISSUE THREAD

**Issue by iambwayne** [MurhafSousli/ngx-scrollbar#618]
Hello Murhaf,

Let me start by saying... Great library.  I made it here after migrating from [ngx-perfect-scrollbar](https://github.com/zefoy/ngx-perfect-scrollbar#readme).  It has been smooth sailing sans this one hurdle.....

#### What are you trying to do?

Use ngx-scrollbar with Kendo UI Grid Component

#### What troubleshooting steps have you tried?

I wrapped the Grid Component with "ng-scrollbar" according to the documentation.  Visually it appears to work.  However, the vertical scrolling behavior is not working properly.  Please note: The Grid Component is using virtualization.  Perhaps something similar to "cdk-virtual-scroll-viewport."

#### Reproduction

[Stackblitz Example](https://stackblitz.com/edit/angular-vgzffw)

Steps to reproduce:
1. Load stackblitz repro
2. Try to scroll vertically
3. Observe scrolling behavior
  
#### Environment

- Angular: 17.3
- ngx-scrollbar: 15.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

Any direction you could provide would be greatly appreciated.

Thank you!

**Comment by MurhafSousli** [comment]
Since the table is using virtual scroll, you need to set the `externalSpacer`, with kendu it is `.k-height-container` and content wrapper should be `.k-grid-table`

```html
<ng-scrollbar externalViewport=".k-grid-content"
                      externalContentWrapper=".k-grid-table"
                      externalSpacer=".k-height-container"
                      asyncDetection>
  <kendo-grid scrollable="virtual">
    ...
  </kendo-grid>
</ng-scrollbar>
```

```css
.k-height-container {
  float: none !important;
  position: absolute !important;
}
```

Here is a [working stackblitz](https://stackblitz.com/edit/angular-vgzffw-ldgsyr?file=src%2Fapp%2Fapp.component.ts,src%2Fstyles.css)

**Comment by iambwayne** [comment]
Murhaf,

WOW..... Holiday weekend and you respond in hours.... Take my money.  Where can I donate?  

One minor detail I noticed.  When you grab the thumb and scroll all the way down to the bottom it keeps scrolling a bit and you lose the thumb.  You can get it back by using the scroll wheel to bring it back into view.  Any ideas?

Thank you again for the quick response.  You rock!

Also, once we get this working as expected, I suggest adding it to the list of examples.  I have worked with several companies that use Telerik controls.  It could be useful.

**Comment by MurhafSousli** [comment]
@iambwayne You can use the sponsor button on the repo and be my first Github sponsor, or make a one time donation if you like!

Regarding that issue, there seem to be a problem with the virtual scroll calculation in the component you're using

You set ` [rowHeight]="36"` but the height rendered is actually `44.89px` for each row, which was caused by the 12px padding applied, this means the virtual scroll is not being calculation properly.

I looked at the original docs, their demo is using another theme `default-ocean-blue.css` where it uses 8px padding, rendered height is now 36px and everything worked as expected, see [fixed stackblitz](
https://stackblitz.com/edit/angular-vgzffw-jjp9rb?file=src%2Fapp%2Fapp.component.ts,src%2Fstyles.css,src%2Findex.html).

Now I realized that the horizontal scrollbar is not displayed. unfortunately, it seems that Kendu UI is using a separate spacer element for the horizontal virtual scroll.
