### ISSUE TITLE
Ngx-scrollbar v15.1.2 Missing scrolled events

### ISSUE THREAD

**Issue by drowhunter** [MurhafSousli/ngx-scrollbar#645]
#### What are you trying to do?

Migrating from v13 I was using the isVericallyScrolled & isHorizontallyScrolled events .

New version seems to have dropped these .

I see that there is now reached and Dropped events in v15.1.3 but on 15.1.2 they don't seem to do anything.

What is the equivalent of this functionality ?since I need to upgrade my angular app to 17 and I rely on this functionality

  
#### Environment

- Angular: 17
- ngx-scrollbar:
- Browser(s): chromium

**Comment by MurhafSousli** [comment]
Yes, the scroll event is dropped since the library no longer uses it, use the native scroll instead!

```html
<ng-scrollbar (scroll)="onScroll($event)">
  ...
</ng-scrollbar>
```
However subscribing to the scroll event in the template is considered a bad approach because it triggers the change detection very frequently, you should subscribe to the scroll event from code outside angular zone.

The following is the right way of using the scroll event:

```ts
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [NgScrollbar],
  template: `
    <ng-scrollbar>
         ...
    </ng-scrollbar>
  `,
})
export class App {

  @ViewChild(NgScrollbar) scrollbarRef: NgScrollbar;

  sub$: Subscription;

  private zone: NgZone = inject(NgZone);

  ngAfterViewInit() {
    this.zone.runOutsideAngular(() => {
       this.sub$ = fromEvent(this.scrollbarRef!.nativeElement, 'scroll').subscribe((e: any) => {
         console.log(e);
      });
    });
  }

  ngOnDestroy() {
    this.sub$?.unsubscribe();
  }
}
```

Regarding the reached events, they are working properly, here is a [working stackblitz](https://stackblitz.com/edit/ngx-scrollbar-spchug) for the scroll and the reached events
