### ISSUE TITLE
Bug with visibility="visible"

### ISSUE THREAD

**Issue by wmaurer** [MurhafSousli/ngx-scrollbar#674]
#### Reproduction

1. Clone MurhafSousli/ngx-scrollbar, install npm packages.
2. Edit `projects/ngx-scrollbar-demo/src/app/example3/example3.component.html` line 4 and add `visibility="visible"`. 
3. `npm run start`, navigate to home page, look at example 3 (Lorem ipsum). Scroll the vertical scrollbar down.
 
 
#### Expected Behavior

The scrollbar thumb should move with the mouse.

#### Actual Behavior

The scrollbar thumb moves upwards when scrolling down.

#### Environment

- Angular: 18.2.11
- ngx-scrollbar: 16.1.0
- Browser(s): Chrome, Edge, Firefox
- Operating System: Linux Manjaro Gnome, Windows 11

**Comment by wmaurer** [comment]
Sorry, I'd thought that adding that one extra property to your own repository would have sufficed as a reproduction.

Here's a Stackblitz:
https://stackblitz.com/~/github.com/wmaurer/ngx-scrollbar-bug

**Comment by wmaurer** [comment]
I have the feeling that this is a timing / change detection problem. I have pushed a branch with a not very elegant workaround. See the change-detection branch:

![image](https://github.com/user-attachments/assets/570bf586-ca5c-4b45-930c-f9842fbd9aab)

In this branch, I have added the following code:

```ts 
export class AppComponent {
  private cdr = inject(ChangeDetectorRef);
  @ViewChild(NgScrollbar) private scrollbar?: NgScrollbar;

  ngOnInit() {
    setTimeout(() => {
      if (this.scrollbar) {
        this.scrollbar.update();
        this.cdr.detectChanges();
      }
    }, 0);
  }
}
```

This fixes the problem, but isn't really a sustainable solution for developers using this component. But maybe it gives you a hint as to what fix you could apply in the ng-scrollbar component?

**Comment by wmaurer** [comment]
And last but not least, it seems that, for this simple example (I haven't yet fully tested in more complex scenarios), upgrading to Angular 19 fixes the problem, without the inelegant workaround above:

https://stackblitz.com/~/github.com/wmaurer/ngx-scrollbar-bug/tree/angular-19

**Comment by MurhafSousli** [comment]
Thanks for the reproduction.

The issue lays in the following code.

https://github.com/MurhafSousli/ngx-scrollbar/blob/379e87e97b63879aaf9f7e7514bf35131a0ae9a7/projects/ngx-scrollbar/src/lib/track/track-adapter.ts#L115-L120

The dimension changed but the track didn't have enough time to render and fit the viewport size, so `this.size` return 0, which caused the issue.

This didn't occur during development, adding `requestAnimationFrame` fixes the issue.

In v19, I learned that the effects now sync with change detection, maybe that why it got fixed in v19 but I will add the fix anyway.
